site_name: N-Queens Problem

plugins:
  - search

theme:
  name: material
  font: false
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode
